### PR TITLE
Could you enable "Issues" on GitHub?

### PR DESCRIPTION
**Pull request by hjfreyer**
This isn't actually a pull request - I'm having an issue with importing ca65 debug symbols, but this repo hasn't enabled the "Issues" feature on GitHub so I don't have any way of reporting the problem.

Would you mind enabling "Issues" and then we can discuss my particular problem in a more suitable setting? 😄

### CODE REVIEW

**Comment by ruby-R53** [comment]
i want that as well, i'm having some issues with Mesen2 here that i wanted to show but i couldn't since we don't have that section lol

**Comment by upintheairsheep** [comment]
Since there is no issues tab, this is a reminder to support the [Famicom Network Controller](https://www.raphnet.net/divers/famicom_network_controller_hvc_051/index_en.php), which is an overclocked NES controller with 16 new buttons.

**Comment by Gumball2415** [comment]
sour has closed the issues tab for a reason.
issues and requests go in the NESDev forum thread.

https://forums.nesdev.org/viewtopic.php?t=24391

**Comment by ruby-R53** [comment]
ah damn i see it now, thanks

**Comment by SourMesen** [comment]
Please use the nesdev forums thread or the nesdev discord instead - the issues tab is closed because I simply don't have enough spare time to process them on top of what already gets reported on the forums/discord.

In general, there are already over 100 pending feature requests on my list that various people have made over time - so any feature request is unlikely to get done anytime soon.  For crashes/bugs, the nesdev forums/discord are the best way to let me know.

**Pull request closed without merging**
