### PR TITLE
MacOS: Handle keyboard outside of Avalonia

### PR DESCRIPTION
**Pull request by angelo-wf**
Avalonia's key-handling (on MacOS Somona at least) seems to have some shortcomings. Most notably: 
- Some keydown-events seem to be dropped entirely. Holding a letter key and pressing an arrow key drops the keydown for the arrow key for example, which makes using the arrow keys for input quite difficult.
- A popup allowing selection of special characters pops up (in the bottom left corner) if certain keys are held down, which then steals focus from the window. This is a MacOS-feature intended for input fields, making typing those characters easier but It looks like Avalonia assumes all key-input to only be for such input.

Some experimentation within the UI indicated that both these problems cannot be (easily) solved through Avalonia as of now. (the popup happens even when no input handlers are registered at all, and using some hacky reflection to gain access to lower-level events still has those keydown-events dropped.)

This PR therefore bypasses Avalonia entirely by adding a new MacOSKeyManager (mirroring the LinuxKeyManager) which listens for and handles key-event locally, before they reach Avalonia at all. This involved:
- Adding a MacOSKeyManager (which has the implementation in Objective-C++) to listen to key-events using Cocoa's `NSEvent addLocalMonitorForEventsMatchingMask:handler:`. It maps MacOS's keycodes to the ones Avalonia uses (because the set-key window still goes through Avalonia and it keeps existing configs compatible).
- Adding a new method to `IKeyManager` to disable local handling and exposing it in the Interop-library, which the UI uses so other windows can still handle key-shortcuts/typing/etc properly. (The implementation is empty in the non-MacOS KeyManagers.)
- Setting up the Makefile to handle compiling Objective-C++ as well, and adding the sources/object files/includes necessary. This is gated behind `MESENOS=osx`, so should only happen when compiling on MacOS.

(I have also looked into adding mouse and controller-support for MacOS and might open PR's for that soon(ish?) as well)

### CODE REVIEW

**Comment by x3ro** [comment]
Nice, just tested this on macOS 13.5.2 and it seems to be working great 🚀

**Comment by SourMesen** [comment]
Thanks for the PR! In general, the macOS side of things is something I can't easily fix/improve on my own, so this is helpful.

I think one thing that would make this a bit simpler/cleaner would be to remove the `_disableHandling` flag and `DisableLocalHandling`/`SetLocalHandlingDisabled` functions entirely and instead use this in the event handler:
```
if(_emu->GetSettings()->CheckFlag(EmulationFlags::InBackground)) {
	return event;
}
```
This should have the same effect and reduce the PR's scope a bit, I think.

One last thing, since this isn't a tiny PR, in general, I'm trying to avoid adding any more GPL-licensed code that I did not write myself to the code. This is to give myself the possibility of changing the license in the future (e.g when I stop working on this project) to something less restrictive than GPL (e.g MIT, BSD, something akin). With that in mind, would you be ok with agreeing that your code here (and in future PRs if you decide to make more macOS-related fixed) is licensed as e.g MIT/BSD/public domain?

**Comment by angelo-wf** [comment]
Pushed a commit to switch to using EmulationFlags::InBackground. And yes, I'm fine with my contributions being relicensed to other licenses like the ones you mentioned.

**Comment by SourMesen** [comment]
Awesome - thanks for the PR!

**Pull request merged**
