### PR TITLE
[CI] AppImage build

### PR DESCRIPTION
**Pull request by qurious-pixel**
This PR was inspired by the work from https://github.com/SourMesen/Mesen2/pull/24

To execute the AppImage run `chmod +x Mesen.AppImage` or select to make executable from the properties menu.

### CODE REVIEW

**Comment by kevin-wijnen** [comment]
Hi there, I'm the author of #24. 👋 I've only just noticed today your message at #24 that you got it to work 

Would've preferred if the changes were just done on #24 itself to reduce the clutter, but that's no issue.

However, I've tested the output of your CI on the Steam Deck (the primary goal of my PR), and it seems to work all fine except for one issue: when running it off an microSD card, it seems to point to a `/tmp/` directory instead of the proper directory (`/run/media/mmcblk0p1/...`, but this might be related to how Valve currently has implemented SD card support with), which causes the "store config in the same directory as the executable" to fail. Forcing the user to try again and choose the profile of the device, instead.

Besides that, it seems to run fine. No errors encountered and a game boots from it.

**Comment by SourMesen** [comment]
Thanks for the time and effort you've both put into this. Sorry for the delay!
I'm not really familiar with appimages in general and haven't had a chance to look into them at all, but since it sounds like it's working, may be useful to others and doesn't affect the code, I'll merge this, thanks!

**Comment by qurious-pixel** [comment]
@SourMesen commit: https://github.com/SourMesen/Mesen2/commit/1cd6d078a71d2288afbdbd36f3ae3542fefa4318 breaks the AppImage.
The Linux appimage uses an override in the makefile to include the .NET framework.

image

L111 sets a default, but allows override.
changing from `?` to `:` disallows .NET framework to be bundled.
https://github.com/SourMesen/Mesen2/blob/168eadd0ee7158bd130effdadbd8ab28159b7a3e/makefile#L111

**Comment by kevin-wijnen** [comment]
> > it seems to point to a /tmp/ directory instead of the proper directory (/run/media/mmcblk0p1/...,
> 
> `/tmp` is the actual working directory for the program. The best way to keep the config files together with the binary is to create a folder called `Mesen.AppImage.config` on your SD card next to Mesen.AppImage, and select "store the data in my user profile".
> 
> All of the files will be together, and is portable.
> 
> image
> 
> Hope this helps @kevin-wijnen

This definitely helped @qurious-pixel, thank you!

I'm preparing some notes regarding the usage on Steam Deck to possibly add it to the README or some other file for user reference. I've stumbled upon some hurdles from "100% perfect" usage, but I mostly got how I wanted it for now. I'll add this info in it as well,

**Pull request merged**
